version: '3.9'
services:
    mysql:
        image: mysql:8.0
        container_name: leapqueue_db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: leapqueue        
        ports:
            - "3306:3306"
        volumes:
            - leapqueue_db_data:/var/lib/mysql
    php:
        build: ./
        volumes:
            - ../:/app
        working_dir: /app
        depends_on:
            - mysql
        entrypoint: ["tail", "-f", "/dev/null"]
volumes:
    leapqueue_db_data:
